---
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning =  FALSE)
knitr::opts_chunk$set(results = 'asis')
library(tidyverse)
library(mgcv)
library(gratia)
options(scipen = 999)
species <- c("warty_sea_cucumber", 
             "Kellets_whelk", 
             "California_spiny_lobster", 
             "white_sea_urchin",
             "garibaldi", 
             "orange_puffball_sponge", 
             "bladder_chain_kelp", 
             "red_sea_urchin", 
             "California_sheephead_male", 
             "bat_star", 
             "giant_kelp", 
             "purple_sea_urchin", 
             "kelp_bass", 
             "sunflower_star", 
             "giant_spined_sea_star", 
             "Coronado_urchin", 
             "red_abalone", 
             "rock_wrasse")
```

``` {r DATA, include=FALSE}
Mod_df <- readr::read_csv("Mixed_Data_2005.csv") |> 
  dplyr::mutate(
    SiteCode = as.factor(SiteCode),
    IslandCode = as.factor(IslandCode),
    ReserveStatus = as.factor(ReserveStatus)) 

```

```{r GAMs, fig.height=8, fig.width=11}
mod <- gam(
  kelp_bass ~ ReserveStatus +
    IslandCode + 
    Mean_ONI_Anom +
    te(SurveyYear, by = interaction(IslandCode, ReserveStatus), k = 15) + 
    s(SiteCode, bs= "re", k=20),
  data = Mod_df, method = 'REML', family = nb())
gam.check(mod)
gratia::appraise(mod, method = "simulate")
gratia::draw(mod, scales = 'free')
sum_mod <- summary(mod)
sum_mod
a <- sum_mod$p.table
a
b <- sum_mod$s.table
b
```

```{r GAMs, fig.height=8, fig.width=11}

mod <- gam(
  kelp_bass ~ ReserveStatus +
    IslandCode + 
    Mean_ONI_Anom +
    te(SurveyYear, by = interaction(IslandCode, ReserveStatus), k = 15) + 
    s(SiteCode, bs= "re", k=20),
  data = Mod_df, method = 'REML', family = nb())

```