---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tmap)
library(tidyverse)
library(sf)
library(here)
library(mgcv)
library(mgcViz)
library(gganimate)
library(gifski)
library(png)
library(av)
library(cowplot)

```

```{r}
Mixed_Data_Types_Wide <- readr::read_csv(here("data", "Mixed_Data_2005.csv")) %>% 
  dplyr::mutate(
    SiteCode = as.factor(SiteCode),
    IslandCode = as.factor(IslandCode),
    ReserveStatus = as.factor(ReserveStatus)) 

GAM_Model <- gam(
  warty_sea_cucumber ~ 
    ReserveStatus +
    IslandCode + 
    Mean_ONI_Anom +
    te(SurveyYear, by = interaction(IslandCode, ReserveStatus), k = 15) + 
    s(SiteCode, bs = "re", k = 20),
  data = Mixed_Data_Types_Wide, method = 'REML', family = nb())

warty_resids <- Mixed_Data_Types_Wide |> 
  select(SiteNumber, IslandCode, IslandName, SiteCode, SiteName, SurveyYear,
         ReserveStatus, Latitude, Longitude, warty_sea_cucumber) |> 
  cbind("residuals" = resid(GAM_Model))

GAM_Model2 <- gam(
  California_spiny_lobster ~ 
    ReserveStatus +
    IslandCode + 
    Mean_ONI_Anom +
    te(SurveyYear, by = interaction(IslandCode, ReserveStatus), k = 15) + 
    s(SiteCode, bs = "re", k = 20),
  data = Mixed_Data_Types_Wide, method = 'REML', family = nb())

lobster_resids <- Mixed_Data_Types_Wide |> 
  select(SiteNumber, IslandCode, IslandName, SiteCode, SiteName, SurveyYear,
         ReserveStatus, Latitude, Longitude, California_spiny_lobster) |> 
  cbind("residuals" = resid(GAM_Model2))

```

```{r}
gam_vis <- getViz(GAM_Model2)
check.gamViz(gam_vis)
```

```{r}
#just making the map sf objects for each island so I can call them more cleanly in the next section(s)
chis <- sf::st_read(
  dsn = here("data", "chis.gpkg"), 
  layer = "chis")
#holy crap this just works!!!

chis_SB <- sf::st_read(
  dsn = here("data", "chis.gpkg"), 
  layer = "chis") |> 
  filter(NAME == "Santa Barbara")

chis_AN <- sf::st_read(
  dsn = here("data", "chis.gpkg"), 
  layer = "chis") |> 
  filter(NAME == "Anacapa")

chis_SC <- sf::st_read(
  dsn = here("data", "chis.gpkg"), 
  layer = "chis") |> 
  filter(NAME == "Santa Cruz")

chis_SR <- sf::st_read(
  dsn = here("data", "chis.gpkg"), 
  layer = "chis") |> 
  filter(NAME == "Santa Rosa")

```

```{r}
plot_resid <- lobster_resids |> 
  filter(SurveyYear == 2019) #cut filter islandcode here... wow! worked!

ggplot() +
  # geom_raster(data = plot_resid, 
  #             aes(x = Longitude, y = Latitude, fill = residuals),
  #             interpolate = T) +
  # scale_fill_viridis_c() +
  geom_sf(data = chis, fill = "grey40") +
  geom_point(data = plot_resid,
             aes(x = Longitude, y = Latitude,
                 color = residuals, size = residuals)) +
  scale_color_viridis_c() +
  # coord_sf(xlim = c(-120.75, -118.75), ylim = c(33.3, 34.6)) +
  theme_classic() +
  theme(legend.position = "bottom")
```


















```{r}

# so this version produces an animation with all the islands in one 

plot_resid <- lobster_resids 

anim <- ggplot() +
  geom_sf(data = chis, fill = "grey40") +
  geom_point(data = plot_resid,
             aes(x = Longitude, y = Latitude,
                 color = residuals, size = abs(residuals))) +
  scale_color_viridis_c() +
  scale_size_continuous(range = c(1,10)) +
  scale_y_continuous(expand = expansion(mult = c(.1, .1))) +
  gganimate::transition_states(SurveyYear, transition_length = 5, state_length = 10) +
  labs(title = '{closest_state}') +
  enter_fade() +
  exit_fade() +
  theme_classic() +
  theme(legend.position = "bottom")
  
  animate(anim, renderer = gifski_renderer())
  #animate(anim, renderer = av_renderer('chis_residuals.mp4'),
          #width = 1280, height = 720, res = 104, fps = 6, detail = 4)  
          #don't really need this but you can't really save a gif and send it on teams so if you want a mp4 output this is how you do it...
```

```{r}
  ###-----------------------------------------------------
  ## okay going after a cowplot - assembled version of four animated plots because scale = free and geom_sf() do NOT play well together and this faceting map thing is an extremely wild rabbit hole out there in the wild west of the internet. I can afford to make 4 graphs and don't NEED to rely on facet_wrap() to do this for me - 
  
  plot_resid <- lobster_resids #can easily change the species here...
  
  resid_SB <- plot_resid |> 
    filter(IslandCode == "SB")
    
  resid_AN <- plot_resid |> 
    filter(IslandCode == "AN")
    
  resid_SC <- plot_resid |> 
    filter(IslandCode == "SC")
    
  resid_SR <- plot_resid |> 
    filter(IslandCode == "SR")
  
  
  SB_anim <- ggplot() +
  geom_sf(data = chis_SB, fill = "grey40") +
  geom_point(data = resid_SB,
             aes(x = Longitude, y = Latitude,
                 color = residuals, size = abs(residuals))) +
  scale_color_viridis_c() +
  scale_size_continuous(range = c(1,10)) +
  scale_y_continuous(expand = expansion(mult = c(.1, .1))) +
  gganimate::transition_states(SurveyYear, transition_length = 5, state_length = 10) +
  labs(title = '{closest_state}') +
  enter_fade() +
  exit_fade() +
  theme_classic() +
  theme(axis.ticks.x = element_blank()) + #goddamn I can't make this go away so whatever
  theme(legend.position = "none")
  
  SB_gif <- animate(SB_anim, width = 240, height = 240, renderer = gifski_renderer())
  SB_gif
  
  AN_anim <- ggplot() +
  geom_sf(data = chis_AN, fill = "grey40") +
  geom_point(data = resid_AN,
             aes(x = Longitude, y = Latitude,
                 color = residuals, size = abs(residuals))) +
  scale_color_viridis_c() +
  scale_size_continuous(range = c(1,10)) +
  scale_y_continuous(expand = expansion(mult = c(.1, .1))) +
  gganimate::transition_states(SurveyYear, transition_length = 5, state_length = 10) +
  labs(title = '{closest_state}') +
  enter_fade() +
  exit_fade() +
  theme_classic() +
    theme(legend.position = "none")
  
  SC_anim <- ggplot() +
  geom_sf(data = chis_SC, fill = "grey40") +
  geom_point(data = resid_SC,
             aes(x = Longitude, y = Latitude,
                 color = residuals, size = abs(residuals))) +
  scale_color_viridis_c() +
  scale_size_continuous(range = c(1,10)) +
  scale_y_continuous(expand = expansion(mult = c(.1, .1))) +
  gganimate::transition_states(SurveyYear, transition_length = 5, state_length = 10) +
  labs(title = '{closest_state}') +
  enter_fade() +
  exit_fade() +
  theme_classic() +
    theme(legend.position = "none")
  
  SR_anim <- ggplot() +
  geom_sf(data = chis_SR, fill = "grey40") +
  geom_point(data = resid_SR,
             aes(x = Longitude, y = Latitude,
                 color = residuals, size = abs(residuals))) +
  scale_color_viridis_c() +
  scale_size_continuous(range = c(1,10)) +
  scale_y_continuous(expand = expansion(mult = c(.1, .1))) +
  gganimate::transition_states(SurveyYear, transition_length = 5, state_length = 10) +
  labs(title = '{closest_state}') +
  enter_fade() +
  exit_fade() +
  theme_classic() +
    theme(legend.position = "none")
  
  legend_anim <- get_legend(SR_anim+
                              theme(legend.position = "bottom"))
  
  #so my thinking here is that instead of anim I can have a baked in plot_grid within animate
  animate(plot_grid(SB_anim, AN_anim, SC_anim, SR_anim), renderer = gifski_renderer())
  
  
  
  
  
  
  
  
  
  
  
  
  
  
 # animate(anim, renderer = av_renderer('chis_residuals.mp4'),
         # width = 1280, height = 720, res = 104, fps = 6, detail = 4)
  
```