---
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning =  FALSE)
library(tidyverse)
library(here)
library(mgcv)
library(gratia)
library(broom)
library(modelr)
# library(itsadug)
# options(scipen = 999)

# The species from our data we are interested in modeling
species <- 
  c("warty_sea_cucumber", 
    "Kellets_whelk",
    "California_spiny_lobster",
    "white_sea_urchin",
    "garibaldi",
    "orange_puffball_sponge",
    "bladder_chain_kelp",
    "red_sea_urchin",
    "California_sheephead_male",
    "bat_star",
    "giant_kelp",
    "purple_sea_urchin",
    "kelp_bass",
    "sunflower_star",
    "giant_spined_sea_star",
    "Coronado_urchin",
    "red_abalone",
    "rock_wrasse")
```

``` {r Wide Data, include=FALSE}
# This data is "mixed" as it contains biomass, count, and percent cover values 
# depends on the species and the next code chunk has "tidy data" with data type
Mixed_Data_Types_Wide <- readr::read_csv(here("data", "Mixed_Data_2005.csv")) %>% 
  dplyr::mutate(
    SiteCode = as.factor(SiteCode),
    IslandCode = as.factor(IslandCode),
    ReserveStatus = as.factor(ReserveStatus)) 

```

```{r Long Data, include=FALSE}
# Mixed data cross reference table with associated data types
Mixed_Data_x_ref <- readr::read_csv(here("data", "Mixed_Data_xref_Fish_Biomass.csv"))

Mixed_Data_Types_Long <- Mixed_Data_Types_Wide %>% 
  pivot_longer(cols = -c(1:10, 167:169), names_to = "Common_Name", values_to = "Data_Value") %>% 
  left_join(Mixed_Data_x_ref %>% select(Common_Name, CommonName, ScientificName, Data_Type)) %>% 
  relocate(Data_Value, .after = ScientificName)
```

```{r}
GAM_Model <- Mixed_Data_Types_Long %>%
  filter(Common_Name %in% species) %>%
  group_by(Common_Name) %>%
  summarise(
    tidy(
      gam(
        Data_Value ~
          ReserveStatus +
          IslandCode +
          Mean_ONI_Anom +
          te(SurveyYear, by = interaction(IslandCode, ReserveStatus), k = 15) +
          s(SiteCode, bs = "re", k = 20),
        method = 'REML', family = nb())
    )
  )
```










```{r}
sp_model <- function(df)
  gam(
    Data_Value ~
      ReserveStatus +
      IslandCode +
      Mean_ONI_Anom +
      te(SurveyYear, by = interaction(IslandCode, ReserveStatus), k = 6) +
      s(Latitude, Longitude, k = 5),
    data = df, method = 'REML', family = nb()
  )

GAMS <- Mixed_Data_Types_Long %>%
  filter(Common_Name %in% species) %>%
  group_by(Common_Name) %>%
  nest() %>%
  mutate(model = map(data, sp_model),
         resids = map2(data, model, add_residuals),
         predictions = map2(data, model, add_predictions))

GAM_resids <- GAMS %>%
  unnest(resids, .drop = TRUE)
```

















```{r}
library(data.table)

library(rlang)
unnest_dt <- function(tbl, col) {

  tbl <- as.data.table(tbl)

  col <- ensyms(col)

  clnms <- syms(setdiff(colnames(tbl), as.character(col)))

  tbl <- as.data.table(tbl)

  tbl <- eval(
    expr(tbl[, as.character(unlist(!!!col)), by = list(!!!clnms)])
  )

  colnames(tbl) <- c(as.character(clnms), as.character(col))

  tbl
}


sp_model <- function(df)
  gam(
    Data_Value ~
      ReserveStatus +
      IslandCode +
      Mean_ONI_Anom +
      te(SurveyYear, by = interaction(IslandCode, ReserveStatus), k = 15) +
      s(SiteCode, bs = "re", k = 20),
    data = df, method = 'REML', family = nb()
  )

GAMS_nest <- Mixed_Data_Types_Long %>%
  filter(Common_Name %in% species) %>%
  group_by(Common_Name) %>%
  nest() %>%
  mutate(model = map(data, sp_model),
         #resids = map2(data, model, add_residuals),
         predictions = map2(data, model, add_predictions))

GAM_predictions <- GAMS_nest %>%
  unnest(predictions)
```


```{r}
GAMS <- Mixed_Data_Types_Long %>% 
  filter(Common_Name %in% species) %>% 
  group_by(Common_Name) %>% 
  summarise(
    tidy(
      gam(
        Data_Value ~ 
          ReserveStatus +
          IslandCode +
          Mean_ONI_Anom +
          te(SurveyYear, by = interaction(IslandCode, ReserveStatus), k = 15) +
          s(SiteCode, bs = "re", k = 20),
        method = 'REML', family = nb()
      )
    )
  )
```




# Testing `mgcv::gam()` model for warty sea cucumbers

```{r GAM Test Model}
GAM_Model <- gam(
  warty_sea_cucumber ~ 
    ReserveStatus +
    IslandCode + 
    Mean_ONI_Anom +
    te(SurveyYear, by = interaction(IslandCode, ReserveStatus), k = 15) + 
    s(SiteCode, bs = "re", k = 20),
  data = Mixed_Data_Types_Wide, method = 'REML', family = nb())
GAM_Model
```

# Using `mgcv::gam.check()` to inspect our fitted gam object

```{r GAM Check}
gam.check(GAM_Model)
```

# Using `gratia::appraise()` for model diagnostics 

```{r GAM Model Gratia Appraise Plots}
gratia::appraise(GAM_Model, method = "simulate")
```

# Using `gratia::draw()`  

```{r GAM Model Gratia Draw Plots, fig.height=8, fig.width=15}
gratia::draw(GAM_Model, scales = 'free')
```

# GAM summary

```{r GAM Summary}
GAM_Model_Summary <- summary.gam(GAM_Model)
GAM_Model_Summary 
```

# Looping through `species` vector

```{r GAMs}

for (spp in species) {
  
  df <- filter(Mixed_Data_Types_Long, Common_Name == spp)
  
  spp_mod <- paste(spp, "GAM", sep = "_")
  
  GAM_Model <- gam(
    Data_Value ~ 
      ReserveStatus +
      IslandCode +
      Mean_ONI_Anom +
      te(SurveyYear, by = interaction(IslandCode, ReserveStatus), k = 15) +
      s(SiteCode, bs = "re", k = 20),
    data = df, method = 'REML', family = nb()) 
  
  # We can call these individually for a cleaner output
  # Look at next code chunk for example on how to call 
  # I call them all here for the quick and dirty output
  
  assign(spp_mod, GAM_Model)
  print(spp_mod)
  print(summary(GAM_Model))
  cat("\n\n\n\n\n") 
  
}

```


```{r}
# summary(warty_sea_cucumber_GAM)
```




```{r}

for (spp in species) {
  
  spp_resids <- paste(spp, "resids", sep = "_")
  spp_mod <- eval(parse(text = paste(spp, "GAM", sep = "_")))
  
  resids <- Mixed_Data_Types_Wide %>% 
    select(SiteNumber, IslandCode, IslandName, SiteCode, SiteName, SurveyYear,
           ReserveStatus, Latitude, Longitude, spp) %>% 
    cbind("residuals" = resid(spp_mod)) %>% 
  dplyr::arrange(desc(Longitude)) %>% 
  dplyr::mutate(SiteCode = fct_inorder(SiteCode))
  
  assign(spp_resids, resids)
}
```

```{r}
for (spp in species) {
  
  spp_resids <- eval(parse(text = paste(spp, "resids", sep = "_")))
  title <- gsub(pattern = "_", replacement = " ", spp) 
    
  p <- ggplot() +
    geom_tile(data = spp_resids, aes(x = SurveyYear, y = SiteCode, fill = residuals)) +
    scale_fill_viridis_c(option = "magma") +
    scale_y_discrete(expand = c(0, 0)) +
    scale_x_continuous(expand = c(0, 0)) +
    # facet_wrap(~IslandCode, ncol = 1, drop = T) +
    labs(title = title) +
    theme_classic()
  print(p)
}
```

